<?php

/**
 * @file
 * Allows the creation of custom dependent contents through the user interface.
 */

/**
 * Implements hook_theme().
 */
function dependent_content_theme() {

  $theme = array(
    'dependent_content' => array(
      'render element' => 'elements',
      'file' => 'dependent_content.page.inc',
      'template' => 'dependent-content'
    ),
    'dependent_content_bundle_list' => array(
      'render element' => 'elements',
      'file' => 'dependent_content.page.inc',
      'template' => 'dependent-content-bundle-list'
    )
  );

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dependent_content_theme_suggestions_dependent_content(array $variables) {

  /** @var \Drupal\dependent_content\Entity\DependentContentInterface $entity */
  $entity = $variables['elements']['#dependent_content'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions = array(
    'dependent_content__' . $sanitized_view_mode,
    'dependent_content__' . $entity->bundle(),
    'dependent_content__' . $entity->bundle() . '__' . $sanitized_view_mode,
    'dependent_content__' . $entity->id(),
    'dependent_content__' . $entity->id() . '__' . $sanitized_view_mode
  );

  return $suggestions;
}
