<?php

/**
 * @file
 * Allows the creation of custom dependent contents through the user interface.
 */

/**
 * Implements hook_theme().
 */
function dependent_content_theme() {

  $theme = array();

  $theme['dependent_content'] = array(
    'render element' => 'elements',
    'file' => 'dependent_content.page.inc',
    'template' => 'dependent-content'
  );

  $theme['dependent_content_bundle_list'] = array(
    'render element' => 'elements',
    'file' => 'dependent_content.page.inc',
    'template' => 'dependent-content-bundle-list'
  );

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dependent_content_theme_suggestions_dependent_content(array $variables) {

  $suggestions = array();
  /** @var \Drupal\dependent_content\Entity\DependentContent $entity */
  $entity = $variables['elements']['#dependent_content'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'dependent_content__' . $sanitized_view_mode;
  $suggestions[] = 'dependent_content__' . $entity->bundle();
  $suggestions[] = 'dependent_content__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'dependent_content__' . $entity->id();
  $suggestions[] = 'dependent_content__' . $entity->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}
